# Generated by Django 3.2.1 on 2021-05-07 16:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessClubs',
            fields=[
                ('club_id', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.TextField(blank=True, null=True, unique=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'fitness_clubs',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('login', models.CharField(max_length=40, unique=True, verbose_name='login')),
                ('role', models.PositiveSmallIntegerField(choices=[(0, 'Пользователь'), (1, 'Тренер'), (2, 'Администратор'), (3, 'Пользователь с абсолютными правами')], default=4, verbose_name='Роль')),
                ('club', models.PositiveSmallIntegerField(choices=[(1, 'Москва, ул. Вильгельма Пика, вл14, 4 этаж (МФК «Хуамин»)'), (2, 'Москва, ул. Архитектора Власова, 22'), (3, 'Москва, Каширское шоссе, 61Г'), (4, 'Москва, ул. Климашкина, 17с2'), (5, 'Санкт-Петербург, Пулковское ш., 35, ТРК Масштаб'), (6, 'Санкт-Петербург, пл. Карла Фаберже, 8, литера Е'), (7, 'Санкт-Петербург, ул. Коллонтай, 31, литера А, корп.1'), (8, 'ул. Ю. Фучика, д. 90')], default=1, verbose_name='Фитнес клуб')),
                ('phone', models.CharField(max_length=40, verbose_name='Телефон')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
