# Generated by Django 3.2.1 on 2021-05-04 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessClubs',
            fields=[
                ('club_id', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.TextField(blank=True, null=True, unique=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'fitness_clubs',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='club_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.fitnessclubs'),
        ),
    ]
