# Generated by Django 3.2.1 on 2021-05-04 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210504_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='club_id',
            new_name='club',
        ),
    ]
