# Generated by Django 3.2.1 on 2021-05-04 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='club',
            field=models.ForeignKey(choices=[(1, 'Москва, ул. Вильгельма Пика, вл14, 4 этаж (МФК «Хуамин»)'), (2, 'Москва, ул. Архитектора Власова, 22'), (3, 'Москва, Каширское шоссе, 61Г'), (4, 'Москва, ул. Климашкина, 17с2'), (5, 'Санкт-Петербург, Пулковское ш., 35, ТРК Масштаб'), (6, 'Санкт-Петербург, пл. Карла Фаберже, 8, литера Е'), (7, 'Санкт-Петербург, ул. Коллонтай, 31, литера А, корп.1'), (8, 'ул. Ю. Фучика, д. 90')], default=1, on_delete=django.db.models.deletion.CASCADE, to='users.fitnessclubs', verbose_name='Фитнес клуб'),
        ),
    ]
