# Generated by Django 3.2.1 on 2021-06-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Пользователь'), (1, 'Тренер')], default=4, verbose_name='Роль'),
        ),
    ]
