# Generated by Django 3.2.1 on 2021-05-04 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.fitnessclubs'),
        ),
    ]
