# Generated by Django 3.2.1 on 2021-05-04 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='club',
            field=models.ForeignKey(choices=[(False, 'Москва, ул. Вильгельма Пика, вл14, 4 этаж (МФК «Хуамин»)'), (False, 'Москва, ул. Архитектора Власова, 22'), (False, 'Москва, Каширское шоссе, 61Г'), (False, 'Москва, ул. Климашкина, 17с2'), (False, 'Санкт-Петербург, Пулковское ш., 35, ТРК Масштаб'), (False, 'Санкт-Петербург, пл. Карла Фаберже, 8, литера Е'), (False, 'Санкт-Петербург, ул. Коллонтай, 31, литера А, корп.1'), (False, 'ул. Ю. Фучика, д. 90')], on_delete=django.db.models.deletion.CASCADE, to='users.fitnessclubs', verbose_name='Фитнес клуб'),
        ),
    ]
