# Generated by Django 3.2.1 on 2021-05-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210504_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Пользователь'), (1, 'Тренер'), (2, 'Администратор'), (3, 'Пользователь с абсолютными правами')], default=4, verbose_name='Роль'),
        ),
    ]
