name: Django CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        ports:
        - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - name: Prepare repo
      uses: actions/checkout@master
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: unit-tests
      run: |
        python fitness_club_cp/fitness_clubs_system/manage.py test main.tests
        python fitness_club_cp/fitness_clubs_system/manage.py test main.test_admin
        python fitness_club_cp/fitness_clubs_system/manage.py test main.test_customer
        python fitness_club_cp/fitness_clubs_system/manage.py test main.test_form_classes_data
        python fitness_club_cp/fitness_clubs_system/manage.py test main.test_instructor
        python fitness_club_cp/fitness_clubs_system/manage.py test main.test_mock
    - name: integration-tests
      run: |
        python fitness_club_cp/fitness_clubs_system/manage.py test main.integration_tests
    - name: E2E-test
      run: |
        python fitness_club_cp/fitness_clubs_system/manage.py test main.E2E_test
        
      
