# Generated by Django 3.2.1 on 2021-06-02 17:41

import datetime
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_alter_customuser_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_instructor', models.TextField(blank=True, null=True)),
                ('add_instructor', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'admin_records',
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('sex', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=50, verbose_name='Отчество')),
                ('day_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('height', models.IntegerField(default=0, verbose_name='Рост')),
                ('measured_weights', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, default=0, null=True), default=[], size=None)),
                ('measure_dates', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(blank=True, default=datetime.date.today, null=True), default=[], size=None)),
                ('tariff_end_date', models.DateField()),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='GroupClasses',
            fields=[
                ('class_id', models.IntegerField(primary_key=True, serialize=False)),
                ('class_name', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'group_classes',
            },
        ),
        migrations.CreateModel(
            name='Instructors',
            fields=[
                ('instructor_id', models.AutoField(primary_key=True, serialize=False)),
                ('sex', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=50, verbose_name='Отчество')),
                ('education', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), size=None, verbose_name='Образование')),
                ('experience', models.IntegerField(verbose_name='Стаж')),
                ('achievements', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), size=None, verbose_name='Достижения')),
                ('specialization', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), size=None, verbose_name='Специализация')),
                ('photo', models.ImageField(default='images/default.jpg', null=True, upload_to='images/', verbose_name='Фото')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'instructors',
            },
        ),
        migrations.CreateModel(
            name='InstructorShedule',
            fields=[
                ('i_shedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('training_time', models.TimeField(blank=True, null=True)),
                ('day_of_week', models.TextField(blank=True, null=True)),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.instructors')),
            ],
            options={
                'db_table': 'instructor_shedule',
            },
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('tariff_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tariff_name', models.TextField(blank=True, null=True, unique=True)),
                ('tariff_description', models.TextField(blank=True, null=True, unique=True)),
                ('price_one_month', models.IntegerField(blank=True, null=True)),
                ('price_three_month', models.IntegerField(blank=True, null=True)),
                ('price_six_month', models.IntegerField(blank=True, null=True)),
                ('price_one_year', models.IntegerField(blank=True, null=True)),
                ('is_time_restricted', models.BooleanField(blank=True, null=True)),
                ('min_time', models.TimeField(blank=True, null=True)),
                ('max_time', models.TimeField(blank=True, null=True)),
                ('days_of_week', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, default='', null=True), default=[], size=None)),
            ],
            options={
                'db_table': 'prices',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('service_id', models.IntegerField(primary_key=True, serialize=False)),
                ('service_name', models.TextField(blank=True, null=True, unique=True)),
                ('service_description', models.TextField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='SpecialOffers',
            fields=[
                ('offer_id', models.AutoField(primary_key=True, serialize=False)),
                ('offer_name', models.TextField(blank=True, null=True)),
                ('offer_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'special_offers',
            },
        ),
        migrations.CreateModel(
            name='InstructorSheduleCustomers',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('training_date', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.customers')),
                ('i_shedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.instructorshedule')),
            ],
            options={
                'db_table': 'instructor_shedule_customers',
            },
        ),
        migrations.CreateModel(
            name='GroupClassesShedule',
            fields=[
                ('shedule_id', models.IntegerField(primary_key=True, serialize=False)),
                ('class_time', models.TimeField(blank=True, null=True)),
                ('day_of_week', models.TextField(blank=True, null=True)),
                ('maximum_quantity', models.IntegerField(blank=True, null=True)),
                ('class_field', models.ForeignKey(blank=True, db_column='class_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.groupclasses')),
                ('club', models.ForeignKey(blank=True, db_column='club_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.fitnessclubs')),
                ('instructor', models.ForeignKey(blank=True, db_column='instructor_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.instructors')),
            ],
            options={
                'db_table': 'group_classes_shedule',
            },
        ),
        migrations.CreateModel(
            name='GroupClassesCustomersRecords',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_date', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.customers')),
                ('shedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.groupclassesshedule')),
            ],
            options={
                'db_table': 'group_classes_customers_records',
            },
        ),
        migrations.AddField(
            model_name='customers',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.instructors'),
        ),
        migrations.AddField(
            model_name='customers',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.prices'),
        ),
        migrations.AddField(
            model_name='customers',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
