# Generated by Django 3.2.1 on 2021-05-07 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_instructor', models.TextField(blank=True, null=True)),
                ('add_instructor', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'admin_records',
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(unique=True)),
                ('sex', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('surname', models.TextField(blank=True, null=True)),
                ('patronymic', models.TextField(blank=True, null=True)),
                ('day_of_birth', models.DateField(blank=True, null=True)),
                ('measure', models.JSONField(blank=True, null=True)),
                ('tariff_end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='GroupClasses',
            fields=[
                ('class_id', models.IntegerField(primary_key=True, serialize=False)),
                ('class_name', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'group_classes',
            },
        ),
        migrations.CreateModel(
            name='Instructors',
            fields=[
                ('instructor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sex', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('surname', models.TextField(blank=True, null=True)),
                ('patronymic', models.TextField(blank=True, null=True)),
                ('education', models.TextField(blank=True, null=True)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('achievements', models.TextField(blank=True, null=True)),
                ('specialization', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'instructors',
            },
        ),
        migrations.CreateModel(
            name='InstructorShedule',
            fields=[
                ('i_shedule_id', models.IntegerField(primary_key=True, serialize=False)),
                ('training_time', models.TimeField(blank=True, null=True)),
                ('day_of_week', models.TextField(blank=True, null=True)),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manager.instructors')),
            ],
            options={
                'db_table': 'instructor_shedule',
            },
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('tariff_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tariff_name', models.TextField(blank=True, null=True, unique=True)),
                ('tariff_description', models.TextField(blank=True, null=True, unique=True)),
                ('price_one_month', models.IntegerField(blank=True, null=True)),
                ('price_three_month', models.IntegerField(blank=True, null=True)),
                ('price_six_month', models.IntegerField(blank=True, null=True)),
                ('price_one_year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'prices',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('service_id', models.IntegerField(primary_key=True, serialize=False)),
                ('service_name', models.TextField(blank=True, null=True, unique=True)),
                ('service_description', models.TextField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='SpecialOffers',
            fields=[
                ('offer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('offer_name', models.TextField(blank=True, null=True)),
                ('offer_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'special_offers',
            },
        ),
        migrations.CreateModel(
            name='InstructorSheduleCustomers',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('training_date', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manager.customers')),
                ('i_shedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manager.instructorshedule')),
            ],
            options={
                'db_table': 'instructor_shedule_customers',
            },
        ),
        migrations.CreateModel(
            name='GroupClassesShedule',
            fields=[
                ('shedule_id', models.IntegerField(primary_key=True, serialize=False)),
                ('class_time', models.TimeField(blank=True, null=True)),
                ('day_of_week', models.TextField(blank=True, null=True)),
                ('maximum_quantity', models.IntegerField(blank=True, null=True)),
                ('class_field', models.ForeignKey(blank=True, db_column='class_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manager.groupclasses')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.fitnessclubs')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manager.instructors')),
            ],
            options={
                'db_table': 'group_classes_shedule',
            },
        ),
        migrations.CreateModel(
            name='GroupClassesCustomersRecords',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_date', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manager.customers')),
                ('shedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manager.groupclassesshedule')),
            ],
            options={
                'db_table': 'group_classes_customers_records',
            },
        ),
        migrations.AddField(
            model_name='customers',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manager.instructors'),
        ),
        migrations.AddField(
            model_name='customers',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manager.prices'),
        ),
        migrations.AddField(
            model_name='customers',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
