# Generated by Django 3.2.1 on 2021-05-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20210523_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructors',
            name='photo',
            field=models.ImageField(default='main/img/trener.jpg', null=True, upload_to='images/'),
        ),
    ]
