# Generated by Django 3.2.1 on 2021-05-25 21:45

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_instructors_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='day_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='patronymic',
            field=models.TextField(blank=True, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='surname',
            field=models.TextField(blank=True, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='instructors',
            name='achievements',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='instructors',
            name='education',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='instructors',
            name='specialization',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), size=None),
        ),
    ]
