# Generated by Django 3.2.1 on 2021-06-01 16:06

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_role'),
        ('manager', '0005_auto_20210601_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.instructors'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.prices'),
        ),
        migrations.AlterField(
            model_name='groupclassescustomersrecords',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.customers'),
        ),
        migrations.AlterField(
            model_name='groupclassescustomersrecords',
            name='shedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.groupclassesshedule'),
        ),
        migrations.AlterField(
            model_name='groupclassesshedule',
            name='class_field',
            field=models.ForeignKey(blank=True, db_column='class_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.groupclasses'),
        ),
        migrations.AlterField(
            model_name='groupclassesshedule',
            name='club',
            field=models.ForeignKey(blank=True, db_column='club_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.fitnessclubs'),
        ),
        migrations.AlterField(
            model_name='groupclassesshedule',
            name='instructor',
            field=models.ForeignKey(blank=True, db_column='instructor_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.instructors'),
        ),
        migrations.AlterField(
            model_name='instructorshedule',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.instructors'),
        ),
        migrations.AlterField(
            model_name='instructorshedulecustomers',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.customers'),
        ),
        migrations.AlterField(
            model_name='instructorshedulecustomers',
            name='i_shedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.instructorshedule'),
        ),
    ]
