# Generated by Django 3.2.1 on 2021-06-03 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20210602_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupclassesshedule',
            name='shedule_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
