# Generated by Django 3.2.1 on 2021-06-04 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_role'),
        ('manager', '0007_alter_prices_tariff_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrators',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.customuser')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('patronym', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'administrators',
            },
        ),
    ]
