# Generated by Django 3.2.1 on 2021-06-04 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20210604_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructors',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.administrators'),
        ),
    ]
