# Generated by Django 3.2.1 on 2021-06-04 13:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_auto_20210604_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminrecords',
            name='add_instructor',
        ),
        migrations.RemoveField(
            model_name='adminrecords',
            name='update_instructor',
        ),
        migrations.AddField(
            model_name='adminrecords',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.administrators'),
        ),
        migrations.AddField(
            model_name='adminrecords',
            name='change',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminrecords',
            name='creation_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 4, 13, 59, 19, 792695)),
        ),
        migrations.AddField(
            model_name='adminrecords',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.instructors'),
        ),
        migrations.AddField(
            model_name='adminrecords',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'pending'), (1, 'active'), (2, 'cancelled')], default=0),
        ),
    ]
