# Generated by Django 3.2.1 on 2021-06-04 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_auto_20210604_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminrecords',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
