# Generated by Django 3.2.1 on 2021-06-06 21:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_auto_20210605_0057'),
    ]

    operations = [

        migrations.AlterField(
            model_name='adminrecords',
            name='creation_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 6, 21, 36, 28, 878425)),
        ),
        migrations.CreateModel(
            name='AdminLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_date', models.DateTimeField(default=datetime.datetime(2021, 6, 6, 21, 36, 28, 880357))),
                ('action', models.PositiveIntegerField(choices=[(0, 'add'), (1, 'delete')])),
                ('description', models.TextField(blank=True, null=True)),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.instructors')),
            ],
            options={
                'db_table': 'admin_logs',
            },
        ),
    ]
