# Generated by Django 3.2.1 on 2021-06-06 21:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_auto_20210606_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminlogs',
            name='instructor',
        ),
        migrations.AlterField(
            model_name='adminlogs',
            name='act_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 6, 21, 51, 8, 65334)),
        ),
        migrations.AlterField(
            model_name='adminrecords',
            name='creation_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 6, 21, 51, 8, 63309)),
        ),
    ]
