# Generated by Django 3.2.1 on 2021-06-06 22:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_auto_20210606_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorPersonalTrainingsLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_date', models.DateTimeField(default=datetime.datetime(2021, 6, 6, 22, 5, 48, 48285))),
                ('action', models.PositiveIntegerField(choices=[(0, 'add'), (1, 'delete')])),
                ('record_id', models.IntegerField(default=None)),
            ],
            options={
                'db_table': 'instructor_personal_trainings_logs',
            },
        ),
        migrations.DeleteModel(
            name='AdminLogs',
        ),

        migrations.AlterField(
            model_name='adminrecords',
            name='creation_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 6, 22, 5, 48, 46196)),
        ),
        migrations.AddField(
            model_name='instructorpersonaltrainingslogs',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.instructors'),
        ),
    ]
