# Generated by Django 3.2.1 on 2021-06-06 23:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_auto_20210606_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorpersonaltrainingslogs',
            name='action',
        ),
        migrations.RemoveField(
            model_name='instructorpersonaltrainingslogs',
            name='record_id',
        ),
        migrations.AddField(
            model_name='instructorpersonaltrainingslogs',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='adminrecords',
            name='creation_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 6, 23, 11, 25, 66442)),
        ),
        migrations.AlterField(
            model_name='instructorpersonaltrainingslogs',
            name='act_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 6, 23, 11, 25, 68400)),
        ),
    ]
