# Generated by Django 3.2.1 on 2021-06-07 00:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_auto_20210606_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminGroupClassesLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_date', models.DateTimeField(default=datetime.datetime(2021, 6, 7, 0, 14, 42, 574586))),
                ('club', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(default='')),
            ],
            options={
                'db_table': 'admin_group_classes_logs',
            },
        ),
        migrations.AlterField(
            model_name='adminrecords',
            name='creation_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 7, 0, 14, 42, 572043)),
        ),
        migrations.AlterField(
            model_name='instructorpersonaltrainingslogs',
            name='act_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 7, 0, 14, 42, 574196)),
        ),
    ]
