# Generated by Django 3.2.1 on 2021-06-07 00:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0018_auto_20210607_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInstructorsInfoLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_date', models.DateTimeField(default=datetime.datetime(2021, 6, 7, 0, 35, 9, 766759))),
                ('description', models.TextField(default='')),
            ],
            options={
                'db_table': 'admin_instructors_info_logs',
            },
        ),
        migrations.DeleteModel(
            name='AdminGroupClassesLogs',
        ),
        migrations.AlterField(
            model_name='adminrecords',
            name='creation_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 7, 0, 35, 9, 762177)),
        ),
        migrations.AlterField(
            model_name='instructorpersonaltrainingslogs',
            name='act_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 7, 0, 35, 9, 766243)),
        ),
        migrations.AddField(
            model_name='admininstructorsinfologs',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.instructors'),
        ),
    ]
