# Generated by Django 3.2.1 on 2021-06-07 00:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0019_auto_20210607_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminGroupClassesLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_date', models.DateTimeField(default=datetime.datetime(2021, 6, 7, 0, 43, 17, 137121))),
                ('club', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(default='')),
            ],
            options={
                'db_table': 'admin_add_group_classes_logs',
            },
        ),

        migrations.AlterField(
            model_name='adminrecords',
            name='creation_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 7, 0, 43, 17, 134514)),
        ),
        migrations.AlterField(
            model_name='instructorpersonaltrainingslogs',
            name='act_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 7, 0, 43, 17, 136762)),
        ),
        migrations.DeleteModel(
            name='AdminInstructorsInfoLogs',
        ),
    ]
