# Generated by Django 3.2.1 on 2021-06-07 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0021_auto_20210607_0102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admingroupclasseslogs',
            old_name='group_class_id',
            new_name='group_class',
        ),
        migrations.AlterField(
            model_name='admingroupclasseslogs',
            name='act_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 7, 17, 54, 25, 154951)),
        ),
        migrations.AlterField(
            model_name='adminrecords',
            name='creation_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 7, 17, 54, 25, 152419)),
        ),
        migrations.AlterField(
            model_name='instructorpersonaltrainingslogs',
            name='act_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 7, 17, 54, 25, 154561)),
        ),
    ]
