# Generated by Django 3.2.1 on 2021-06-07 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0022_auto_20210607_1754'),
    ]
    operations = [
        migrations.AlterField(
            model_name='admingroupclasseslogs',
            name='act_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 7, 18, 2, 40, 283207)),
        ),
        migrations.AlterField(
            model_name='adminrecords',
            name='creation_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 7, 18, 2, 40, 280875)),
        ),
        migrations.AlterField(
            model_name='instructorpersonaltrainingslogs',
            name='act_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 7, 18, 2, 40, 282805)),
        ),
        migrations.AlterModelTable(
            name='admingroupclasseslogs',
            table='admin_group_classes_logs',
        ),
    ]
