# Generated by Django 3.2.1 on 2021-06-09 15:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0023_auto_20210607_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructors',
            name='new_photo',
            field=models.ImageField(default='images/default.jpg', null=True, upload_to='images/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='admingroupclasseslogs',
            name='act_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 9, 15, 28, 54, 835281)),
        ),
        migrations.AlterField(
            model_name='adminrecords',
            name='creation_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 9, 15, 28, 54, 832858)),
        ),
        migrations.AlterField(
            model_name='customers',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.prices', verbose_name='тариф'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='tariff_end_date',
            field=models.DateField(verbose_name='Дата окончания срока действия абонемента'),
        ),
        migrations.AlterField(
            model_name='instructorpersonaltrainingslogs',
            name='act_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 9, 15, 28, 54, 834859)),
        ),
    ]
