# Generated by Django 3.2.1 on 2021-10-09 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0026_auto_20211009_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructors',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='admingroupclasseslogs',
            name='act_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 9, 15, 39, 18, 238961)),
        ),
        migrations.AlterField(
            model_name='adminrecords',
            name='creation_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 9, 15, 39, 18, 236802)),
        ),
        migrations.AlterField(
            model_name='instructorpersonaltrainingslogs',
            name='act_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 9, 15, 39, 18, 238641)),
        ),
    ]
