# Generated by Django 3.2.1 on 2021-10-13 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0028_auto_20211011_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admingroupclasseslogs',
            name='act_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 13, 12, 8, 34, 347975)),
        ),
        migrations.AlterField(
            model_name='adminrecords',
            name='creation_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 13, 12, 8, 34, 345638)),
        ),
        migrations.AlterField(
            model_name='instructorpersonaltrainingslogs',
            name='act_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 13, 12, 8, 34, 347502)),
        ),
        migrations.AlterModelTable(
            name='instructors',
            table='instructors',
        ),
    ]
