# Generated by Django 3.2.1 on 2021-10-13 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0030_auto_20211013_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admingroupclasseslogs',
            name='act_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 13, 12, 22, 5, 316825)),
        ),
        migrations.AlterField(
            model_name='adminrecords',
            name='creation_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 13, 12, 22, 5, 314527)),
        ),
        migrations.AlterField(
            model_name='instructorpersonaltrainingslogs',
            name='act_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 13, 12, 22, 5, 316431)),
        ),
        migrations.AlterField(
            model_name='instructors',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
